title: John Doe # your name (or website title) here
logo: "/images/IMG_9082.jpeg?raw=true" # headshot goes here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/sophie-lee-835b32201">View my LinkedIn profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
